# UI & Font
font_family      FiraCode Nerd Font
font_size        12.0
window_padding_width 15

# Reze Color Palette
background #1a1a1a
foreground #e0e0e0
cursor     #ff007f
selection_background #2b1055

# Color blocks (Neon Pink & Deep Purple accents)
color0  #1a1a1a
color8  #4d4d4d
color1  #ff007f
color9  #ff4d94
color2  #2b1055
color10 #4c1d95
color3  #ffcc00
color11 #ffdb4d
color4  #8a2be2
color12 #9b30ff
color5  #ff007f
color13 #ff66b2
color6  #00e5ff
color14 #66ffff
color7  #e0e0e0
color15 #ffffff

# Transparency & KDE Wayland Blur
background_opacity 0.85
linux_display_server wayland
shell zsh
